name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
    - name: Install dependencies
      run: |
        cd Ergo
        dotnet restore
    - name: Build
      run: |
        cd Ergo
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd Ergo.Tests
        dotnet test Ergo.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./../coverage.xml --verbosity normal
    - name: Build solution and generate NuGet package
      run: |
        cd Ergo
        dotnet pack -c Release -o out  
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./Ergo/out/*.nupkg -k ${{ secrets.NUGET_KEY }} --skip-duplicate --no-symbols true
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: 4966c84d-99c1-426c-9ebd-15fb26e355d8
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
